[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "visualkit"
version = "0.0.1"
description = "An Video Editor engine library."
readme = "README.md"
authors = [
    { name = "Suraj Airi", email = "surajairi.ml@gmail.com" }
]
license = { text = "MIT license" }
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.13.5",
]

[dependency-groups]
dev = [
    "notebook>=7.6.2",
    "pyperclip>=1.11.0",
    "pytest-async>=0.1.1",
    "ruff>=0.12.1",
]


[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

