from importlib.metadata import PackageNotFoundError, version

from visualkit.engine import AssetResolver, DictAssetResolver, TimelinePipeline
from visualkit.exporters import BaseExporter, DaVinciResolveExporter, FFmpegVideoExporter
from visualkit.models import (
    KEYFRAMEABLE_PROPERTIES,
    MASK_PROPERTIES,
    AddClipResult,
    AnimationPreset,
    AudioClip,
    AudioContent,
    AudioProperties,
    AudioTrack,
    BaseClip,
    ChromaKey,
    Clip,
    ClipAnimation,
    CodedVisualClip,
    CompileStatus,
    CompoundAudioClip,
    CompoundClip,
    CurveSpec,
    Easing,
    ExposedParameter,
    InsertMode,
    Keyframe,
    LintIssue,
    Mask,
    MediaClip,
    Position,
    PropertyCurve,
    RenderMode,
    Size,
    Source,
    TextClip,
    TextGradient,
    TextStyle,
    Timeline,
    Track,
    TrackKind,
    Transform,
    Variable,
    VariableType,
    VideoTrack,
    VisualClip,
    VisualContent,
    color_to_rgb,
)
from visualkit.utils.exceptions import (
    BrowserNotFoundError,
    CodedVisualCompileError,
    CodedVisualError,
    ExportError,
    InvalidTimeError,
    MissingSourceError,
    TemplateParameterError,
    TimelineValidationError,
    VisualKitError,
)
from visualkit.utils.time import Time

try:
    __version__ = version("visualkit")
except PackageNotFoundError:  # running from a source checkout that is not installed
    __version__ = "0+unknown"

__all__ = [
    "__version__",
    "AddClipResult",
    "AudioClip",
    "AudioContent",
    "AudioProperties",
    "AudioTrack",
    "BaseClip",
    "Clip",
    "CodedVisualClip",
    "CompileStatus",
    "CompoundAudioClip",
    "CompoundClip",
    "ExposedParameter",
    "InsertMode",
    "LintIssue",
    "MediaClip",
    "Position",
    "RenderMode",
    "Size",
    "Source",
    "TextClip",
    "TextStyle",
    "Timeline",
    "Track",
    "TrackKind",
    "Transform",
    "Variable",
    "VariableType",
    "VideoTrack",
    "VisualClip",
    "VisualContent",
    "Time",
    "TimelinePipeline",
    "AssetResolver",
    "DictAssetResolver",
    "BaseExporter",
    "DaVinciResolveExporter",
    "FFmpegVideoExporter",
    # exceptions
    "VisualKitError",
    "InvalidTimeError",
    "TimelineValidationError",
    "TemplateParameterError",
    "MissingSourceError",
    "CodedVisualError",
    "ExportError",
    "CodedVisualCompileError",
    "BrowserNotFoundError",
    "TextGradient",
    "AnimationPreset",
    "ClipAnimation",
    "ChromaKey",
    "Mask",
    "MASK_PROPERTIES",
    "color_to_rgb",
    "Easing",
    "Keyframe",
    "PropertyCurve",
    "CurveSpec",
    "KEYFRAMEABLE_PROPERTIES",
]
