from importlib.metadata import PackageNotFoundError, version

from visualkit.engine import AssetResolver, DictAssetResolver, TimelinePipeline
from visualkit.exporters import BaseExporter, DaVinciResolveExporter, FFmpegVideoExporter
from visualkit.models import (
    AudioClip,
    AudioContent,
    AudioProperties,
    AudioTrack,
    BaseClip,
    Clip,
    CodedVisualClip,
    CompileStatus,
    CompoundAudioClip,
    CompoundClip,
    ExposedParameter,
    InsertMode,
    MediaClip,
    Position,
    RenderMode,
    Size,
    Source,
    TextClip,
    TextStyle,
    Timeline,
    Track,
    TrackKind,
    Transform,
    Variable,
    VariableType,
    VideoTrack,
    VisualClip,
    VisualContent,
)
from visualkit.utils.exceptions import (
    BrowserNotFoundError,
    CodedVisualCompileError,
    CodedVisualError,
    ExportError,
    InvalidTimeError,
    MissingSourceError,
    TemplateParameterError,
    TimelineValidationError,
    VisualKitError,
)
from visualkit.utils.time import Time

try:
    __version__ = version("visualkit")
except PackageNotFoundError:  # running from a source checkout that is not installed
    __version__ = "0+unknown"

__all__ = [
    "__version__",
    "AudioClip",
    "AudioContent",
    "AudioProperties",
    "AudioTrack",
    "BaseClip",
    "Clip",
    "CodedVisualClip",
    "CompileStatus",
    "CompoundAudioClip",
    "CompoundClip",
    "ExposedParameter",
    "InsertMode",
    "MediaClip",
    "Position",
    "RenderMode",
    "Size",
    "Source",
    "TextClip",
    "TextStyle",
    "Timeline",
    "Track",
    "TrackKind",
    "Transform",
    "Variable",
    "VariableType",
    "VideoTrack",
    "VisualClip",
    "VisualContent",
    "Time",
    "TimelinePipeline",
    "AssetResolver",
    "DictAssetResolver",
    "BaseExporter",
    "DaVinciResolveExporter",
    "FFmpegVideoExporter",
    # exceptions
    "VisualKitError",
    "InvalidTimeError",
    "TimelineValidationError",
    "TemplateParameterError",
    "MissingSourceError",
    "CodedVisualError",
    "ExportError",
    "CodedVisualCompileError",
    "BrowserNotFoundError",
]
